forge "http://forge.puppetlabs.com"

mod "example42/yum"
mod "nginx",
    :git => "git://github.com/jfryman/puppet-nginx.git"
mod "proletaryo/supervisor"
mod "jenkins",
    :git => "git://github.com/jenkinsci/puppet-jenkins.git"
